# Generated by Django 5.2.1 on 2025-06-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_alter_sparepart_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
