# Generated by Django 5.2.1 on 2025-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_partcategory_remove_sparepart_supplier_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
