# Generated by Django 5.2.1 on 2025-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_sparepart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
