# Generated by Django 5.2.1 on 2025-06-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_sparepart_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.partcategory'),
        ),
    ]
