# Generated by Django 5.2.1 on 2025-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_sparepart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='procurement_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
